DATA SEGMENT
MSG1 DB,0DH,0AH,"ENTER NUMBER:$";
MSG2 DB,0DH,0AH,"EVEN$";
MSG3 DB,0DH,0AH,"ODDD$";
DATA ENDS

CODE SEGMENT
ASSUME DS:DATA,CS:CODE
START:
	MOV AX,DATA
	MOV DS,AX
	MOV DX,OFFSET MSG1
	MOV AH,09H
	INT 21H
	MOV AH,01H
	INT 21H
	ROR AL,01H ;DATA IS STORED IN AL AND ROTATED RIGHT USING ROR BY 1 PLACE
	JNC A1 ;WILL JUMP TO A1 IF THERE IS NO CARRY JNC=JUMP IF NO CARRY
	MOV DX,OFFSET MSG3
	MOV AH,09H
	INT 21H
	JMP A2
	A1:MOV DX,OFFSET MSG2
	MOV AH,09H
	INT 21H
	A2:MOV AH,4CH
	INT 21H
CODE ENDS
END START