DATA SEGMENT
MSG1 DB,0DH,0AH,"ENTER NUMBER$"
MSG2 DB,0DH,0AH,"LARGEST NUMBER:$"
DATA ENDS

CODE SEGMENT
ASSUME DS:DATA,CS:CODE
START:
	MOV AX,DATA
	MOV DS,AX
	MOV SI,2000H ;STACK
	MOV CL,05H
	MOV [SI],00H ;address of stack
	
L1:	MOV DX,OFFSET MSG1
	MOV AH,09H  ;print msg
	INT 21H
	MOV AH,01H ;input
	INT 21H 
	CMP AL,[SI]
	JGE L3 ; jump if greater than

L4:	DEC CL
	CMP CL,00H
	JNZ L1 ; jump if not zero
	JMP L5  ;jump

L3:	MOV [SI],AL
	JMP L4


L5:	MOV DX,OFFSET MSG2
	MOV AH,09H ; to print
	INT 21H
	MOV BL,[SI] 
	MOV DL,BL
	MOV AH,02H 
	INT 21H
	MOV AH,4CH ;exit
	INT 21H
CODE ENDS
END START
