PRINT MACRO MSG
	MOV DX,OFFSET MSG
	MOV AH,09H
	INT 21H
ENDM

DATA SEGMENT
MSG1 DB 0DH,0AH,"ENTER FIRST NUMBER:$"
MSG2 DB 0DH,0AH,"ENTER SECOND NUMBER:$"
MSG3 DB 0DH,0AH,"MULTIPLICATION IS:$"
DATA ENDS

CODE SEGMENT
ASSUME DS:DATA,CS:CODE
START:	MOV AX,DATA
		MOV DS,AX
		PRINT MSG1
		MOV AH,01H
		INT 21H
		SUB AL,30H ; TO CONVERT NUM INTO ASCII VALUE
		MOV BL,AL
		PRINT MSG2
		MOV AH,01H
		INT 21H
		SUB AL,30H
		PRINT MSG3
		MUL BL
		AAM 		;ASCII ADJUSTMENT AFTER MULTIPLICATION, CORRECTS THE RESULT AFTER MULTIPLICATION
		ADD AL,30H
		ADD AH,30H
		MOV CX,AX
		MOV DL, ; c higher
		MOV AH,02H ; WRITE CHARACTER TO STD OUTPUT
        INT 21H
		MOV DL,CL ; c lower
		MOV AH,02H
		INT 21H
		MOV AH,4CH
		INT 21H
CODE ENDS
END START