DATA SEGMENT
M1 DB 0DH,0AH,"ENTER THE STRING : $"
M2 DB 0DH,0AH,"THE ENTERED STRING NOT PALINDROME $"
M3 DB 0DH,0AH,"THE ENTERED STRING IS PALINDROME $"
DATA ENDS

CODE SEGMENT
ASSUME CS:CODE, DS:DATA
START:	MOV AX,DATA
	MOV DS, AX
	MOV SI,4000H
	MOV DI,6000H
	MOV DX, OFFSET M1
	MOV AH, 09H
	INT 21H
L1:	MOV AH, 01H
	INT 21H

	MOV [SI], AL
	MOV [DI],AL
	INC SI
	INC DI
	CMP AL, 0DH
	JNZ L1
	DEC SI
	DEC SI
	MOV DI,6000H
L3:	MOV BL, [SI]
	CMP BL,[DI]
	JNZ L2
	DEC SI
	INC DI
	MOV AL,[DI]
	CMP AL,0DH
	JNZ L3
	MOV DX,OFFSET M3
	MOV AH,09H
	INT 21H
	JMP L4
L2: MOV DX,OFFSET M2
	MOV AH,09H
	INT 21H
	JMP L4
L4:	MOV AH,4CH
	INT 21H
CODE ENDS
END START
