DATA SEGMENT
MSG1 DB 0DH,0AH,"HELLO BITCHES$"
DATA ENDS

CODE SEGMENT
ASSUME DS:DATA,CS:CODE
START:	MOV AX,DATA
		MOV DS,AX
		MOV DX,OFFSET MSG1
		MOV AH,09H
		INT 21H
		MOV AH,4CH
		INT 21H
CODE ENDS
END START
		